In [1]:
import numpy as np

In [2]:
myList = [1,2,3,4,5,6,7]

In [3]:
myList

[1, 2, 3, 4, 5, 6, 7]

In [4]:
myMatrix = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
myMatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(myMatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.random.rand(3)

array([0.67752733, 0.44504099, 0.63125029])

In [8]:
np.random.rand(10)

array([0.74096835, 0.80701318, 0.00609046, 0.43274426, 0.94945419,
       0.16139657, 0.12888952, 0.99796609, 0.9467211 , 0.14328958])

In [10]:
myValues = np.random.rand(10,10)

myValues

In [11]:
myValues

array([[0.79727024, 0.28712849, 0.57400307, 0.00289149, 0.72643405,
        0.24792595, 0.5994965 , 0.30054787, 0.79483894, 0.31801736],
       [0.96680747, 0.2090586 , 0.20915617, 0.97311227, 0.76695144,
        0.24999928, 0.28073024, 0.96141156, 0.37153893, 0.60797636],
       [0.97738707, 0.95980504, 0.64588066, 0.75158866, 0.92770223,
        0.79352402, 0.86609428, 0.97536961, 0.6433591 , 0.33242701],
       [0.10508962, 0.72431379, 0.16257833, 0.76028938, 0.58811322,
        0.44425543, 0.62589234, 0.77147748, 0.246647  , 0.52432866],
       [0.39754985, 0.60122112, 0.32805368, 0.9562656 , 0.40759949,
        0.61664499, 0.54089775, 0.62526256, 0.51382988, 0.14421322],
       [0.4144067 , 0.37252924, 0.66229028, 0.80936405, 0.55513639,
        0.6767193 , 0.66381738, 0.35674428, 0.25479115, 0.63798715],
       [0.26305661, 0.06715983, 0.05850499, 0.43010829, 0.86001211,
        0.17748481, 0.30407082, 0.39328543, 0.27685842, 0.24828395],
       [0.48557189, 0.19872235, 0.7512415

In [12]:
myValues.max()

0.998056194182212

In [13]:
myValues.min()

0.0028914907016143188

In [14]:
myValues.argmax()

77

In [15]:
myValues.argmin()

3